### PR TITLE
[IMP] Allow changing client in activity

### PR DESCRIPTION
**Pull request by victor-champonnois**
[Task](https://gestion.coopiteasy.be/web#id=1061&view_type=form&model=project.task&action=479)

Allow to change the client in Activity when the state is draft or canceled.

### CODE REVIEW

**Review by robinkeunen — COMMENTED** [review]
J'ai pas été clair : il faut vérifier l'état des sale orders plutot que l'état des activités, non?

**Comment by victor-champonnois** [comment]
fixed by keeping only the condition `('state','not in',['draft', 'cancelled'])`

**Review by robinkeunen — APPROVED** [review]
LGTM: do not forget to rebase and squash commits

**Pull request merged**
